services: 
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: transaction-app
    restart: always
    working_dir: /var/www
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.27.3-alpine
    container_name: transaction-nginx
    restart: always
    ports: 
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d 
  db: 
    container_name: transaction-db
    image: mysql
    volumes: 
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transactions_db
    ports:
      - 3306:3306